# fly.toml app configuration file generated for battle-city on 2026-04-29T09:42:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'battle-city'
primary_region = 'yyz'

[build]

[[services]]
  internal_port = 3536
  protocol = "tcp"
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
